Updating integration tests MCollective template
So we connect to RabbitMQ using 127.0.0.1 instead of localhost, since
Travis is failing on:

    self.my_name = socket.gethostbyname(socket.gethostname())

with:

    gaierror: [Errno -2] Name or service not known

Not really sure if this change will fix the issue.